import { Colors } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const recipeDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 32,
  },
  errorText: {
    marginTop: 16,
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    fontWeight: "500",
  },
  imageContainer: {
    position: "relative",
    width: "100%",
    height: 300,
  },
  recipeImage: {
    width: "100%",
    height: "100%",
  },
  actionButtonsContainer: {
    position: "absolute",
    top: 16,
    right: 16,
    flexDirection: "column",
    gap: 12,
  },
  actionButton: {
    borderRadius: 20,
    padding: 8,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  mealPlanButton: {
    backgroundColor: "rgba(76, 175, 80, 0.9)",
  },
  favoriteButton: {
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  contentContainer: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -24,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  recipeTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#2C3E50",
    marginBottom: 16,
    lineHeight: 34,
  },
  infoBadgesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 20,
  },
  infoBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  infoBadgeText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  section: {
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#2C3E50",
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  description: {
    fontSize: 16,
    lineHeight: 24,
    color: "#555",
    fontStyle: "italic",
  },
  authorContainer: {
    gap: 12,
  },
  authorInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  authorText: {
    fontSize: 16,
    color: "#444",
    fontWeight: "500",
  },
  sourceInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sourceText: {
    fontSize: 14,
    color: "#666",
    fontStyle: "italic",
  },
  allergensContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  allergenBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFEBEE",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
    borderWidth: 1,
    borderColor: "#FFCDD2",
  },
  allergenText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#D32F2F",
  },
  allergenFreeContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  allergenFreeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E8",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
    borderWidth: 1,
    borderColor: "#C8E6C9",
  },
  allergenFreeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#2E7D32",
  },
  ingredientsContainer: {
    gap: 16,
  },
  enhancedIngredientItem: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
  },
  ingredientHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  ingredientNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  ingredientNumberText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FFF",
  },
  ingredientMainInfo: {
    flex: 1,
  },
  ingredientName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 4,
  },
  ingredientQuantityContainer: {
    alignSelf: "flex-start",
  },
  ingredientQuantity: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.primary,
    backgroundColor: "#FFF",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  ingredientNotes: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  ingredientNotesText: {
    fontSize: 14,
    color: "#666",
    fontStyle: "italic",
    flex: 1,
  },
  nutritionContainer: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 16,
  },
  nutritionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  nutritionLabel: {
    fontSize: 16,
    color: "#444",
    fontWeight: "500",
  },
  nutritionValue: {
    fontSize: 16,
    color: "#2C3E50",
    fontWeight: "600",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 16,
  },
  statItem: {
    alignItems: "center",
    gap: 4,
  },
  statLabel: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
  },
  statValue: {
    fontSize: 16,
    color: "#2C3E50",
    fontWeight: "600",
  },
  metadataContainer: {
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 16,
    gap: 12,
  },
  metadataItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metadataLabel: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  metadataValue: {
    fontSize: 14,
    color: "#2C3E50",
    fontWeight: "600",
  },
  placeholderText: {
    fontSize: 16,
    color: "#999",
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 20,
  },
  bottomSpacing: {
    height: 40,
  },
});